### ISSUE TITLE
Note Label Misalignment

### ISSUE THREAD

**Issue by PhotonicGluon** [AudiTranscribe/AudiTranscribe#22]
## What is the bug?

The note labels are not centered.

## How do you reproduce it?

Steps to reproduce the behaviour:

1. Open a project.
2. Look at the note labels.

## What is expected?

The note labels should be properly centred.

## What is actually happening?

The note labels are slightly off-center.

## (Optional) Screenshots

<img src="https://user-images.githubusercontent.com/25820201/198989093-e8f833d5-f2aa-4baf-8477-9045c1ea8f18.jpg" height=500 alt="Imprecision">

## System Information

Please complete the following information:

- OS: macOS
- Version: 13.0 (22A380)

## Application Information

Please complete the following information:

- Application Version: Version 0.8.3

**Comment by PhotonicGluon** [comment]
Note label alignment is much better now:
<img src="https://user-images.githubusercontent.com/25820201/199004067-a43aba39-b757-4183-b893-dd897eba7951.jpg" alt="Imprecision Fix" height=500>

Differences in alignment should be negligible.

**Comment by Oxyhydride** [comment]
With the fix, the issue still persists on Windows:
<img src="https://user-images.githubusercontent.com/59317720/199744774-cbb0e45a-d9e4-410b-a1de-af692720f401.jpg" alt="Windows Misalignment">

**Comment by Oxyhydride** [comment]
Hmm seems like the issue was due to improper font configuration on Windows. It seems to have been fixed now
