### ISSUE TITLE
Fix Variable Names For "Music Key"

### ISSUE THREAD

**Issue by PhotonicGluon** [AudiTranscribe/AudiTranscribe#24]
Fix incorrect terminology of "music key" when it is, in fact, a music **scale**.

**Comment by Oxyhydride** [comment]
But isn't the thing that AudiTranscribe offers actually music **keys**, not **scales**?

From [Wikipedia](https://en.wikipedia.org/wiki/Scale_(music)):
> In [music theory](https://en.wikipedia.org/wiki/Music_theory), a scale is any set of musical [notes](https://en.wikipedia.org/wiki/Note_(music)) ordered by [fundamental frequency](https://en.wikipedia.org/wiki/Fundamental_frequency) or [pitch](https://en.wikipedia.org/wiki/Pitch_(music)).

and from this [other article](https://en.wikipedia.org/wiki/Key_(music)):

> In [music theory](https://en.wikipedia.org/wiki/Music_theory), the key of a piece is the group of pitches, or [scale](https://en.wikipedia.org/wiki/Scale_(music)), that forms the basis of a [musical composition](https://en.wikipedia.org/wiki/Musical_composition) in [classical](https://en.wikipedia.org/wiki/Classical_music), Western art, and Western pop music.

from that same article:
> A scale is an ordered set of notes typically used in a key, while the key is the "center of gravity" established by particular [chord progressions](https://en.wikipedia.org/wiki/Chord_progression)

From [pianoscales.org](https://www.pianoscales.org/difference-keys-scales.html):
> A key is a collection of tones and it is common to say that a piece of music is written in the key of… For example, a song that includes the [chords](https://www.pianoscales.org/chords.html) G, C, D and Em are most likely in the key of G. That is because all the tones that belongs to the four chords also belongs to the key of G (which are G, A, B, C, D, E, F#).
>
> It is true that the G Major Scale includes the same tones: G, A, B, C, D, E and F#. But a song in the key of G could at the same time include several scales. For example, a guitarist playing a blues song in the key of A may use both the pentatonic minor and major scales.

So I believe that music **key** is actually the correct term to use here instead of **scale**.
