### ISSUE TITLE
Cancelling Saving Project Incorrectly Shows Saving Progress Bar

### ISSUE THREAD

**Issue by Oxyhydride** [AudiTranscribe/AudiTranscribe#28]
## What is the bug?

When saving a project (e.g. initial save of the project, or by using the "Save As..." option), cancelling the file select will still show the progress bar.

## How do you reproduce it?

Steps to reproduce the behaviour:

1. Create a new project on Windows
2. Attempt to save
3. On the file select dialog, click cancel

## What is expected?

A popup saying "No file selected" is to be shown, and the progress bar should not appear.

## What is actually happening?

No popup appears, and the progress bar for saving appears.
(The progress bar will appear indefinitely and will not go way)

## System Information

Please complete the following information:

- OS: Windows
- Version: 22H2 (OS Build 19045.2193)

## Application Information

Please complete the following information:

- Application Version: Version 0.8.3

**Comment by PhotonicGluon** [comment]
Apparently this also occurs on other platforms.
